# Generated by Django 4.2.8 on 2024-01-01 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pub_Date',
            new_name='pub_date',
        ),
    ]
